branch-defaults:
  default:
    environment: null
  master:
    environment: session-test-env
    group_suffix: null
global:
  application_name: session-test
  default_ec2_keyname: ec2-jenkins
  default_platform: PHP 7.1
  default_region: us-west-2
  profile: eb-cli
  sc: git
